# Configuración del Conversor de Archivos TIFF
# Este archivo permite personalizar el comportamiento de los conversores

# Configuración de formatos de salida
formats:
  # Conversor JPG 400 DPI (alta resolución)
  JPGHIGH:
    enabled: true                    # Habilitar conversión a JPG 400 DPI
    quality: 95                      # Calidad de compresión (1-100)
    optimize: true                   # Optimizar archivo
    progressive: false               # JPEG progresivo
    dpi: 400                        # Resolución en DPI
  
  # Conversor JPG 200 DPI (media resolución)
  JPGLOW:
    enabled: true                    # Habilitar conversión a JPG 200 DPI
    quality: 90                      # Calidad de compresión (1-100)
    optimize: true                   # Optimizar archivo
    progressive: false               # JPEG progresivo
    dpi: 200                        # Resolución en DPI
  
  # Conversor PDF con EasyOCR (alternativa local)
  PDF:
    enabled: true                    # ✅ HABILITAR EasyOCR
    resolution: 300                  # Resolución en DPI
    page_size: "A4"                 # Tamaño de página
    fit_to_page: true                # Ajustar imagen a la página
    ocr_language: ["es", "en"]      # Lista de idiomas para OCR
    ocr_confidence: 0.2             # Confianza mínima para OCR (0.0-1.0)
    create_searchable_pdf: true      # Crear PDF con texto buscable
    use_gpu: true                  # Usar GPU si está disponible

# Configuración de procesamiento
processing:
  max_workers: 1                     # Número máximo de workers paralelos
  batch_size: 2                     # Tamaño del lote de procesamiento
  overwrite_existing: false          # Sobrescribir archivos existentes

# Configuración de salida
output:
  create_subdirectories: true        # Crear subdirectorios por formato
  naming_pattern: "{original_name}"  #"{original_name}_{format}_{dpi}"  # Patrón de nombres con DPI

# Configuración de metadatos MET
METS:
  enabled: true                      # Habilitar generación de archivos MET
  include_image_metadata: true       # Incluir metadatos técnicos de imagen
  include_file_metadata: true        # Incluir metadatos del archivo
  include_processing_info: true      # Incluir información de procesamiento
  metadata_standard: 'MET'           # Estándar METS
  organization: 'Grupo API'          # Nombre de la organización
  creator: 'Sistema Automatizado'    # Sistema creador
  generate_all_met: false            # true: archivos con timestamp, false: un archivo por formato

# Configuración de postconversores
postconverters:
  # Postconversor MET por formato
  met_format:
    enabled: true                    # Habilitar generación de archivos MET por formato
    include_image_metadata: true     # Incluir metadatos técnicos de imagen
    include_file_metadata: true      # Incluir metadatos del archivo
    include_processing_info: true    # Incluir información de procesamiento
    metadata_standard: 'MET'         # Estándar METS
    organization: 'Grupo API'        # Nombre de la organización
    creator: 'Sistema Automatizado'  # Sistema creador

# Notas:
# - Los valores se pueden modificar según las necesidades
# - Para agregar nuevos formatos, crear nuevas secciones siguiendo el patrón
# - Los conversores se cargan dinámicamente desde el código
# - Este archivo se puede especificar con --config en la línea de comandos
# - JPGHIGH y JPGLOW crean versiones de alta y media resolución respectivamente
# - PDF está habilitado como única opción de OCR
# - Tesseract y Azure OCR están deshabilitados
