# Configuración de ejemplo para el Conversor MET
# Este archivo muestra las diferentes opciones de configuración

# Configuración de formatos de salida
formats:
  jpg_400:
    enabled: true
    quality: 95
    dpi: 400
  
  jpg_200:
    enabled: true
    quality: 90
    dpi: 200
  
  pdf_easyocr:
    enabled: true
    resolution: 300
    ocr_language: ["es", "en"]

# Configuración de metadatos MET - OPCIÓN 1: Archivos con timestamp
met_metadata_timestamp:
  enabled: true
  include_image_metadata: true
  include_file_metadata: true
  include_processing_info: true
  metadata_standard: 'MET'
  organization: 'Mi Organización'
  creator: 'Sistema de Conversión'
  generate_all_met: true  # Genera archivos como: MET_JPG_400_20250825_143656.xml
  
# Configuración de metadatos MET - OPCIÓN 2: Un archivo por formato
met_metadata_single:
  enabled: true
  include_image_metadata: true
  include_file_metadata: true
  include_processing_info: true
  metadata_standard: 'MET'
  organization: 'Mi Organización'
  creator: 'Sistema de Conversión'
  generate_all_met: false  # Genera archivos como: jpg_400.xml, pdf_easyocr.xml

# Configuración de procesamiento
processing:
  max_workers: 4
  overwrite_existing: false

# Configuración de salida
output:
  create_subdirectories: true
