name: Pylint

on: [push]

jobs:
  pylint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - name: Checkout código
      uses: actions/checkout@v5
    - name: Configurar Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analizar código con pylint
      run: |
        pylint src/ main.py --disable=C0114,C0115,C0116 --max-line-length=100
